config/routes.rb
Rails.application.routes.draw do
  root "items#index"
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'profile'
      patch 'profile_update'
      get 'logout'
    end
    collection do
      get 'ready'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/deliver_address.rb
class DeliverAddress < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/delivery_day.rb
class DeliveryDay < ApplicationRecord
  has_many :items
end

app/models/delivery_way.rb
class DeliveryWay < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one    :purchase
  belongs_to :category
  belongs_to :brand
  has_many   :likes, dependent: :destroy
  has_many   :comments
  has_one    :shipping, dependent: :destroy
  accepts_nested_attributes_for :shipping
  belongs_to :size, optional: true
  has_many   :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  belongs_to :item, optional: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  belongs_to :item, optional: true
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items
  has_ancestry
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
has_many :likes, dependent: :destroy
has_many :comments
has_one  :deliver_address
accepts_nested_attributes_for :deliver_address
has_many :items, through: :purchases
has_many :purchases
has_one  :card
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
  end

  def new
    @item = Item.new
    @item.images.new
  end

  def create
  end
  
end

app/helpers/brand_helper.rb
module BrandHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.haml
  -# = render 'ヘッダーのファイル先'

  -# メインの部分
  = form_with(model: @item, local: true, multipart: true) do |f|
    .sell__container
      .sell__container__main
        .sell__container__main__wrapper
          .sell__container__main__wrapper--head
            %h2 商品の情報を入力


            -# 画像投稿フォーム
          .sell__container__main__wrapper__sell-upload
            %label
              出品画像
            %span.form-require
              必須
            %p 最大10枚までアップロードできます
          #image-box
            #previews
              - if @item.persisted?
                - @item.item_images.each_with_index do |image, i|
                  = image_tag image.imagesrc, data: { index: i }, width: "100", height: '100'

                -# 画像投稿フォームを整理したらcameraアイコンの設置箇所を正す
                %i.fas.fa-camera

                -# 商品名の部分
        .sell__container__main__form
          .sell__container__main__form__group
            %label
              商品名
              %span.form-require
                必須
              = f.text_field :name, class: "sell__container__main__form__group__input", placeholder: "40文字まで"
            %label
              商品の説明
              %span.form-require
                必須
            = f.text_area :description, { class: 'sell__textarea-default', placeholder: '商品の説明(必須 1,000文字以内)(色、素材、重さ、定価、注意点など)例)2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。', rows: '5' }
            = render partial: 'error-messages', locals: {product: f.object, column: 'name'}

            -# 商品の詳細部分
        .sell__container__main__form.clearfix
          %h3.sell__container__main__form__sub-head 
            商品の詳細
          .sell__container__main__form__box
            .sell__container__main__form__box__category
              %label
                カテゴリー
                %span.form-require
                  必須
                  -# ancestryで設定したあとコーディング
                  %i.fas.fa-angle-down
            .sell__container__main__form__box__brand
              %label
                ブランド
                  %span.form-require_brand
                    任意
              .sell__container__main__form__box__brand__select
                = f.fields_for :brand do |b|
                  = b.text_field :name, placeholder: '例）シャネル'
            .sell__container__main__form__box__condition
              %label
                商品の状態
                %span.form-require
                  必須
              .sell__container__main__form__box__condition__select
                = f.select :condition, Item.conditions.keys, {prompt: "---"},{class:"  "}

          -# 配送についての部分
        .sell__container__main__delivery
          %h3.sell__container__main__delivery__sub-head
            配送について
          = link_to "#"
          .sell__container__main__delivery__box
            .sell__container__main__delivery__box__top
              %label
                配送料の負担
                %span.form-require
                  必須
              .sell__container__main__delivery__box__select
                = f.select :fee_burden, Shipping.fee_burdens.keys, {prompt: "---"},{class: " "}
            .sell__container__main__delivert__box__middle
              %label
                発送元の地域
                %span.form-require
                  必須
              .sell__container__main__delivery__box__select
                = f.select :area, Shipping.areas.keys, {prompt: "---"},{class: " "}
            .sell__container__main__delivery__box__bottom
              %label
                発送までの日数
                %span.form-require
                  必須
              .sell__container__main__delivery__box__select
                = f.select :handling_time, Shipping.handling_times.keys, {prompt: "---"},{class: " "}

          -# 価格の部分
        .sell__container__main__price
          %h3.sell__container__main__price__sub-head
            販売価格(¥300~9,999,999)
            -# link_toを追加
            



          -# 出品する,下記に保存,もどるのボタンの部分


          -# = render 'フッターのファイル先'

app/views/items/_sell-tab.html.haml
.sell-tab
  .sell-tab__box
    .sell-tab__box--text
      = link_to '出品', root_path, class:"sell-tab__box--text"
    .sell-tab__box--logo
      %i.fas.fa-camera

app/views/items/create.html.haml
.item-sell-wrapper
  .sell-form-wrapper
    = render 'shared/form-header'
    .sell-notification.form-container
      %h3.sell-notification__title 出品が完了しました
      %span<> 出品した商品は「
      = link_to '出品した商品', exhibition_users_path, class: 'sell-notification__link'
      %span<> 」からいつでも見ることができます
      .item-btn-area
        .item-btn-area__container
          .item-btn-area__container__box
            = link_to '続けて出品する', new_item_path, class: 'item-btn item-btn-link'
        .item-btn-area__container
          .item-btn-area__container__box
            = link_to '出品した商品を見る', item_path(@item), class: 'item-btn item-btn-link'
      = link_to 'マイページを見る', user_path(current_user), class: 'sell-notification__link'
    = render 'shared/form-footer'

app/views/items/new.html.haml
.sell-form-wrapper
  = render partial: 'form'